//------------------------------------------------------------------------------
//  CashTransaction.cs
//
//  Implementation of: CashTransaction (Class) <<ef-entity>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 02-jun-2017 10:49:09
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Budget.Core.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DFlow.Transactions.Core.Model
{
	public class CashTransaction
	{
		public CashTransaction()
		{
		}

		public virtual decimal Amount { get;  set; }

		public virtual BudgetLine BudgetLine { get; set; }

		public virtual int? BudgetLine_Id { get; set; }

		[Required]
		[MaxLength(250)] // Default string length
		public virtual string Currency { get;  set; }

		public virtual DateTime Date { get;  set; }

		[Required]
		[MaxLength(250)] // Default string length
		public virtual string Description { get;  set; }

		public int Id { get; set; }

		[MaxLength(1000)]
		public virtual string Notes { get; set; }

		public virtual Byte[] RowVersion { get; set; }
	}
}