//------------------------------------------------------------------------------
//  BudgetClassManager.cs
//
//  Implementation of: BudgetClassManager (Class) <<entity-manager>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 02-jun-2017 10:49:07
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Budget.Core.Model;
using DFlow.Budget.Core.Services;
using DFlow.Budget.Lib.Data;
using DFlow.Tennants.Core.Model;
using Domion.Core.Services;
using Domion.Lib.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Linq.Expressions;

namespace DFlow.Budget.Lib.Services
{
    public class BudgetClassManager : BaseRepository<BudgetClass, int>, IQueryManager<BudgetClass>, IEntityManager<BudgetClass, int>, IBudgetClassManager
    {
        public static string duplicateByNameError = @"There's another BudgetClass with Name ""{0}"", can't duplicate! (Id={1})";

        private Expression<Func<BudgetClass, bool>> _baseFilter;
        private Tennant _currentTennant;

        public BudgetClassManager(BudgetDbContext dbContext, Tennant currentTennant)
            : base(dbContext)
        {
            _currentTennant = currentTennant;

            _baseFilter = (bc) => bc.Tennant_Id == _currentTennant.Id;
        }

        public BudgetClass FindDuplicateByName(BudgetClass entity)
        {
            if (entity.Id == 0)
            {
                return Query(bc => bc.Name == entity.Name.Trim()).SingleOrDefault();
            }
            else
            {
                return Query(bc => bc.Name == entity.Name.Trim() && bc.Id != entity.Id).SingleOrDefault();
            }
        }

        public override IQueryable<BudgetClass> Query(Expression<Func<BudgetClass, bool>> where)
        {
            return base.Query(where).Where(_baseFilter);
        }

        public virtual BudgetClass Refresh(BudgetClass entity)
        {
            base.Detach(entity);

            return Find(entity.Id);
        }

        public new virtual IEnumerable<ValidationResult> TryDelete(BudgetClass entity)
        {
            return base.TryDelete(entity);
        }

        public new virtual IEnumerable<ValidationResult> TryInsert(BudgetClass entity)
        {
            if (entity.RowVersion != null && entity.RowVersion.Length > 0) throw new InvalidOperationException("RowVersion not empty on Insert");

            CommonSaveOperations(entity);

            return base.TryInsert(entity);
        }

        public new virtual IEnumerable<ValidationResult> TryUpdate(BudgetClass entity)
        {
            if (entity.RowVersion == null || entity.RowVersion.Length == 0) throw new InvalidOperationException("RowVersion empty on Update");

            CommonSaveOperations(entity);

            return base.TryUpdate(entity);
        }

        public virtual IEnumerable<ValidationResult> TryUpsert(BudgetClass entity)
        {
            if (entity.Id == 0)
            {
                return TryInsert(entity);
            }
            else
            {
                return TryUpdate(entity);
            }
        }

        internal virtual void CommonSaveOperations(BudgetClass entity)
        {
            TrimStrings(entity);
        }

        protected override IEnumerable<ValidationResult> ValidateDelete(BudgetClass entity)
        {
            yield break;
        }

        protected override IEnumerable<ValidationResult> ValidateSave(BudgetClass entity)
        {
            BudgetClass duplicateByName = FindDuplicateByName(entity);

            if (duplicateByName != null)
            {
                yield return new ValidationResult(string.Format(duplicateByNameError, duplicateByName.Name, duplicateByName.Id), new[] { "Name" });
            }

            yield break;
        }

        private void TrimStrings(BudgetClass entity)
        {
            if (entity.Name != null) entity.Name = entity.Name.Trim();
        }
    }
}
