//------------------------------------------------------------------------------
//  TennantsDbContext.cs
//
//  Implementation of: TennantsDbContext (Class) <<dbcontext>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 05-jun-2017 20:08:13
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Tennants.Core.Model;
using Domion.Lib.Data;
using Microsoft.EntityFrameworkCore;
using NLog;
using System;

namespace DFlow.Tennants.Lib.Data
{
	public class TennantsDbContext : DbContext
	{
		private static Logger logger = LogManager.GetCurrentClassLogger();

		public TennantsDbContext()
			: base()
		{
		}

		public TennantsDbContext(DbContextOptions<TennantsDbContext> options)
			: base(options)
		{
		}

		// Para hacer efectivo el modo del DbContext se debe cambiar el Tag DOMION::IsolatedContext
		// en el DbContext del Modelo PIM, ejecutar la Transformación y generar el código nuevamente,
		// porque ese parámetro afecta la generación de las clases del Modelo de Dominio

		public static bool IsolatedContext
		{
			get { return false; }
		}

		public override int SaveChanges()
		{
			try
			{
				return base.SaveChanges();
			}
			catch (Exception ex)
			{
				logger.Error(ex);

				throw;
			}
		}

		/// 
		/// <param name="modelBuilder"></param>
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			ConfigureLocalModel(modelBuilder);

			if (!IsolatedContext)
			{
				ConfigureExternalModel(modelBuilder);
			}
		}

		/// 
		/// <param name="modelBuilder"></param>
		private void ConfigureExternalModel(ModelBuilder modelBuilder)
		{
		}

		/// 
		/// <param name="modelBuilder"></param>
		private void ConfigureLocalModel(ModelBuilder modelBuilder)
		{
			// Database schema is "Tennants"

			modelBuilder.AddConfiguration(new TennantConfiguration());
		}
	}
}