//------------------------------------------------------------------------------
//  TennantConfiguration.cs
//
//  Implementation of: TennantConfiguration (Class) <<entity-configuration>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 05-jun-2017 20:08:13
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Tennants.Core.Model;
using Domion.Lib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DFlow.Tennants.Lib.Data
{
	public class TennantConfiguration : EntityTypeConfiguration<Tennant>
	{
		public override void Map(EntityTypeBuilder<Tennant> builder)
		{
			builder.ToTable("Tennants", schema: "Tennants");

			builder.HasKey(t => t.Id);

			builder.Property(t => t.RowVersion)
				.IsRowVersion();

			builder.HasIndex(t => t.Owner)
				.IsUnique();
		}
	}
}