//------------------------------------------------------------------------------
//  BudgetLineConfiguration.cs
//
//  Implementation of: BudgetLineConfiguration (Class) <<entity-configuration>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 04-jul-2017 23:57:07
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Budget.Core.Model;
using Domion.Lib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DFlow.Budget.Lib.Data
{
	public class BudgetLineConfiguration : EntityTypeConfiguration<BudgetLine>
	{
		public override void Map(EntityTypeBuilder<BudgetLine> builder)
		{
			builder.ToTable("BudgetLines", schema: "Budget");

			builder.HasKey(bl => bl.Id);

			builder.Property(bl => bl.RowVersion)
				.IsRowVersion();

			builder.HasOne<BudgetClass>(bl => bl.BudgetClass)
				.WithMany(bc => bc.BudgetLines)
				.HasForeignKey(bl => bl.BudgetClass_Id)
				.OnDelete(DeleteBehavior.Cascade);

			// Indexes

			builder.HasIndex(bl => bl.Name)
				.IsUnique();
		}
	}
}