//------------------------------------------------------------------------------
//  ITenantManager.cs
//
//  Implementation of: ITenantManager (Interface) <<entity-manager>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 05-jun-2017 20:08:13
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Tenants.Core.Model;
using Domion.Core.Services;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Linq.Expressions;

namespace DFlow.Tenants.Core.Services
{
	public interface ITenantManager : IQueryManager<Tenant>, IEntityManager<Tenant, int>
	{
		Tenant Refresh(Tenant entity);

		void SaveChanges();

		IEnumerable<ValidationResult> TryDelete(Tenant entity);

		IEnumerable<ValidationResult> TryInsert(Tenant entity);

		IEnumerable<ValidationResult> TryUpdate(Tenant entity);

		IEnumerable<ValidationResult> TryUpsert(Tenant entity);
	}
}