//------------------------------------------------------------------------------
//  IBankAccountManager.cs
//
//  Implementation of: IBankAccountManager (Interface) <<entity-manager>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 02-jun-2017 10:49:09
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Transactions.Core.Model;
using Domion.Core.Services;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DFlow.Transactions.Core.Services
{
    public interface IBankAccountManager : IEntityManager<BankAccount, int>
    {
        BankAccount Refresh(BankAccount entity);

        void SaveChanges();

        IEnumerable<ValidationResult> TryDelete(BankAccount entity);

        IEnumerable<ValidationResult> TryInsert(BankAccount entity);

        IEnumerable<ValidationResult> TryUpdate(BankAccount entity);

        IEnumerable<ValidationResult> TryUpsert(BankAccount entity);
    }
}
