//------------------------------------------------------------------------------
//  ICashTransactionManager.cs
//
//  Implementation of: ICashTransactionManager (Interface) <<entity-manager>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 02-jun-2017 10:49:10
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Transactions.Core.Model;
using Domion.Core.Services;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DFlow.Transactions.Core.Services
{
    public interface ICashTransactionManager : IQueryManager<CashTransaction>, IEntityManager<CashTransaction, int>
    {
        CashTransaction Refresh(CashTransaction entity);

        void SaveChanges();

        IEnumerable<ValidationResult> TryDelete(CashTransaction entity);

        IEnumerable<ValidationResult> TryInsert(CashTransaction entity);

        IEnumerable<ValidationResult> TryUpdate(CashTransaction entity);

        IEnumerable<ValidationResult> TryUpsert(CashTransaction entity);
    }
}
