//------------------------------------------------------------------------------
//  Tenant.cs
//
//  Implementation of: Tenant (Class) <<ef-entity>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 05-jun-2017 20:08:13
//  Original author: Miguel
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DFlow.Tenants.Core.Model
{
	public class Tenant
	{
		public Tenant()
		{
		}

		public int Id { get; set; }

		[MaxLength(250)] // Default string length
		public virtual string Owner { get; set; } // Key data ----------

		public virtual Byte[] RowVersion { get; set; }
	}
}