//------------------------------------------------------------------------------
//  CashTransactionConfiguration.cs
//
//  Implementation of: CashTransactionConfiguration (Class) <<entity-configuration>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 02-jun-2017 10:49:09
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Budget.Core.Model;
using DFlow.Transactions.Core.Model;
using Domion.Lib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DFlow.Transactions.Lib.Data
{
    public class CashTransactionConfiguration : EntityTypeConfiguration<CashTransaction>
    {
        public override void Map(EntityTypeBuilder<CashTransaction> builder)
        {
            builder.ToTable("CashTransactions", schema: "Transactions");

            builder.HasKey(ct => ct.Id);

            builder.Property(ct => ct.RowVersion)
                .IsRowVersion();

            // External etities

            builder.HasOne<BudgetLine>(ct => ct.BudgetLine)
                .WithMany()
                .HasForeignKey(ct => ct.BudgetLine_Id)
                .OnDelete(DeleteBehavior.Restrict);
        }
    }
}
