//------------------------------------------------------------------------------
//  TagConfiguration.cs
//
//  Implementation of: TagConfiguration (Class) <<entity-configuration>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 02-jun-2017 10:49:10
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Transactions.Core.Model;
using Domion.Lib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DFlow.Transactions.Lib.Data
{
    public class TagConfiguration : EntityTypeConfiguration<Tag>
    {
        public override void Map(EntityTypeBuilder<Tag> builder)
        {
            builder.ToTable("Tags", schema: "Transactions");

            builder.HasKey(t => t.Id);

            builder.Property(t => t.RowVersion)
                .IsRowVersion();

            builder.HasIndex(t => t.Name)
                .IsUnique();
        }
    }
}
