//------------------------------------------------------------------------------
//  ITennantManager.cs
//
//  Implementation of: ITennantManager (Interface) <<entity-manager>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 05-jun-2017 20:08:13
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Tennants.Core.Model;
using Domion.Core.Services;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Linq.Expressions;

namespace DFlow.Tennants.Core.Services
{
	public interface ITennantManager : IQueryManager<Tennant>, IEntityManager<Tennant, int>
	{
		Tennant Refresh(Tennant entity);

		void SaveChanges();

		IEnumerable<ValidationResult> TryDelete(Tennant entity);

		IEnumerable<ValidationResult> TryInsert(Tennant entity);

		IEnumerable<ValidationResult> TryUpdate(Tennant entity);

		IEnumerable<ValidationResult> TryUpsert(Tennant entity);
	}
}