//------------------------------------------------------------------------------
//  IBudgetLineManager.cs
//
//  Implementation of: IBudgetLineManager (Interface) <<entity-manager>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 02-jun-2017 10:49:09
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Budget.Core.Model;
using Domion.Core.Services;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Linq.Expressions;

namespace DFlow.Budget.Core.Services
{
	public interface IBudgetLineManager : IEntityManager<BudgetLine, int>
	{
		BudgetLine Refresh(BudgetLine entity);

		void SaveChanges();

		IEnumerable<ValidationResult> TryDelete(BudgetLine entity);

		IEnumerable<ValidationResult> TryInsert(BudgetLine entity);

		IEnumerable<ValidationResult> TryUpdate(BudgetLine entity);

		IEnumerable<ValidationResult> TryUpsert(BudgetLine entity);

		IEnumerable<ValidationResult> ValidateDelete(BudgetLine entity);

		IEnumerable<ValidationResult> ValidateSave(BudgetLine entity);
	}
}