//------------------------------------------------------------------------------
//  TenantsDbContext.cs
//
//  Implementation of: TenantsDbContext (Class) <<dbcontext>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 04-jul-2017 23:57:10
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Tenants.Core.Model;
using Domion.Lib.Data;
using Microsoft.EntityFrameworkCore;
using NLog;
using System;

namespace DFlow.Tenants.Lib.Data
{
	public class TenantsDbContext : DbContext
	{
		private static Logger logger = LogManager.GetCurrentClassLogger();

		public TenantsDbContext()
			: base()
		{
		}

		public TenantsDbContext(DbContextOptions<TenantsDbContext> options)
			: base(options)
		{
		}

		public override int SaveChanges()
		{
			try
			{
				return base.SaveChanges();
			}
			catch (Exception ex)
			{
				logger.Error(ex);

				throw;
			}
		}

		/// 
		/// <param name="modelBuilder"></param>
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			ConfigureLocalModel(modelBuilder);

			ConfigureExternalModel(modelBuilder);
		}

		/// 
		/// <param name="modelBuilder"></param>
		private void ConfigureExternalModel(ModelBuilder modelBuilder)
		{
		}

		/// 
		/// <param name="modelBuilder"></param>
		private void ConfigureLocalModel(ModelBuilder modelBuilder)
		{
			// Database schema is "Tenants"

			modelBuilder.AddConfiguration(new TenantConfiguration());
		}
	}
}