//------------------------------------------------------------------------------
//  TenantConfiguration.cs
//
//  Implementation of: TenantConfiguration (Class) <<entity-configuration>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 04-jul-2017 23:57:10
//  Original author: Miguel
//------------------------------------------------------------------------------

using DFlow.Tenants.Core.Model;
using Domion.Lib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DFlow.Tenants.Lib.Data
{
	public class TenantConfiguration : EntityTypeConfiguration<Tenant>
	{
		public override void Map(EntityTypeBuilder<Tenant> builder)
		{
			builder.ToTable("Tenants", schema: "Tenants");

			builder.HasKey(t => t.Id);

			builder.Property(t => t.RowVersion)
				.IsRowVersion();

			// Indexes

			builder.HasIndex(t => t.Owner)
				.IsUnique();
		}
	}
}